# Generated by Django 5.2.1 on 2025-05-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invoices/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '02 - Recibo',
                'verbose_name_plural': '02 - Recibos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detected_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('fuel', models.CharField(choices=[('0', 'Nenhum'), ('1', 'Elétrico'), ('2', 'Álcool'), ('3', 'Gasolina'), ('4', 'Diesel')], default='0', max_length=1, verbose_name='Combustível')),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': '01 - Veículo',
                'verbose_name_plural': '01 - Veículos',
            },
        ),
    ]
